format_version: '2.0'

# old file name: heavy_false-unreach-call.c
input_files: 'heavy-1.c'

properties:
  - property_file: ../properties/unreach-call.prp
    expected_verdict: false

options:
  language: C
  data_model: ILP32
