format_version: '2.0'

# old file name: linear_sea.ch_true-unreach-call.c
input_files: 'linear_sea.ch.c'

properties:
  - property_file: ../properties/unreach-call.prp
    expected_verdict: true
  - property_file: ../properties/coverage-branches.prp
  - property_file: ../properties/coverage-conditions.prp
  - property_file: ../properties/coverage-statements.prp

options:
  language: C
  data_model: ILP32
