format_version: '2.0'

# old file name: linear_search_false-unreach-call.c
input_files: 'linear_search.c'

properties:
  - property_file: ../properties/unreach-call.prp
    expected_verdict: false
  - property_file: ../properties/coverage-error-call.prp
  - property_file: ../properties/coverage-branches.prp
  - property_file: ../properties/coverage-conditions.prp
  - property_file: ../properties/coverage-statements.prp

options:
  language: C
  data_model: ILP32
