format_version: '2.0'

# old file name: veris.c_NetBSD-libc__loop_true-unreach-call_true-termination.i
input_files: 'veris.c_NetBSD-libc_loop.i'

properties:
  - property_file: ../properties/termination.prp
    expected_verdict: true
  - property_file: ../properties/unreach-call.prp
    expected_verdict: true

options:
  language: C
  data_model: ILP32
