format_version: '2.0'

# old file name: vogal_true-unreach-call.i
input_files: 'vogal-1.i'

properties:
  - property_file: ../properties/unreach-call.prp
    expected_verdict: true
  - property_file: ../properties/coverage-branches.prp
  - property_file: ../properties/coverage-conditions.prp
  - property_file: ../properties/coverage-statements.prp

options:
  language: C
  data_model: ILP32
