format_version: '2.0'

# old file name: while_infinite_loop_2_true-unreach-call_false-termination.c
input_files: 'while_infinite_loop_2.c'

properties:
  - property_file: ../properties/termination.prp
    expected_verdict: false
  - property_file: ../properties/unreach-call.prp
    expected_verdict: true

options:
  language: C
  data_model: ILP32
