format_version: '2.0'

# old file name: Mono3_false-unreach-call1.c
input_files: 'Mono3_1.c'

properties:
  - property_file: ../properties/unreach-call.prp
    expected_verdict: false

options:
  language: C
  data_model: ILP32
