format_version: '2.0'

input_files: 'nested_delay_notd2.c'

properties:
  - property_file: ../properties/unreach-call.prp
    expected_verdict: false
  - property_file: ../properties/coverage-error-call.prp
  - property_file: ../properties/coverage-branches.prp

options:
  language: C
  data_model: ILP32
