format_version: '2.0'

# old file name: nested3_false-unreach-call.c
input_files: 'nested3-2.c'

properties:
  - property_file: ../properties/unreach-call.prp
    expected_verdict: false

options:
  language: C
  data_model: ILP32
