format_version: '2.0'

# old file name: aiob_4_true-unreach-call.c.v+cfa-reducer.c
input_files: 'aiob_4.c.v+cfa-reducer.c'

properties:
  - property_file: ../properties/unreach-call.prp
    expected_verdict: true

options:
  language: C
  data_model: ILP32
