format_version: '2.0'

# old file name: ofuf_2_true-unreach-call.c
input_files: 'ofuf_2.c'

properties:
  - property_file: ../properties/unreach-call.prp
    expected_verdict: true

options:
  language: C
  data_model: ILP32
