format_version: '2.0'
input_files: 'egcd2-ll_valuebound10.c'
properties:
  - property_file: ../properties/unreach-call.prp
    expected_verdict: true
  - property_file: ../properties/no-overflow.prp
    expected_verdict: true
  - property_file: ../properties/coverage-branches.prp

options:
  language: C
  data_model: ILP32
