format_version: '2.0'

# old file name: array_true-unreach-call1_true-termination.c
input_files: 'array_1-2.c'

properties:
  - property_file: ../properties/termination.prp
    expected_verdict: true
  - property_file: ../properties/unreach-call.prp
    expected_verdict: true

options:
  language: C
  data_model: ILP32
